CREATE DATABASE addressbook;

USE addressbook;

CREATE TABLE `address_type` (
  `ADDRESS_TYPE_ID` int NOT NULL AUTO_INCREMENT,
  `ADDRESS_TYPE_NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  PRIMARY KEY (`ADDRESS_TYPE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `country` (
  `COUNTRY_ID` int NOT NULL AUTO_INCREMENT,
  `COUNTRY_NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `COUNTRY_CODE` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  PRIMARY KEY (`COUNTRY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `city` (
  `CITY_ID` int NOT NULL AUTO_INCREMENT,
  `CITY_NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `COUNTRY_ID` int NOT NULL,
  PRIMARY KEY (`CITY_ID`),
  KEY `fk_city_country_idx` (`COUNTRY_ID`),
  CONSTRAINT `fk_city_country` FOREIGN KEY (`COUNTRY_ID`) REFERENCES `country` (`COUNTRY_ID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `person` (
  `PERSON_ID` int NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `LAST_NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `EDU_LEVEL` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  PRIMARY KEY (`PERSON_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `address` (
  `ADDRESS_ID` int NOT NULL AUTO_INCREMENT,
  `ADDRESS` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `POSTCODE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `CITY_ID` int NOT NULL,
  `PERSON_ID` int NOT NULL,
  `ADDRESS_TYPE_ID` int DEFAULT NULL,
  PRIMARY KEY (`ADDRESS_ID`),
  KEY `fk_address_city1_idx` (`CITY_ID`),
  KEY `fk_address_person1_idx` (`PERSON_ID`),
  KEY `fk_address_adress_type1_idx` (`ADDRESS_TYPE_ID`),
  CONSTRAINT `fk_address_adress_type1` FOREIGN KEY (`ADDRESS_TYPE_ID`) REFERENCES `address_type` (`ADDRESS_TYPE_ID`) ON DELETE SET NULL,
  CONSTRAINT `fk_address_city1` FOREIGN KEY (`CITY_ID`) REFERENCES `city` (`CITY_ID`) ON DELETE CASCADE,
  CONSTRAINT `fk_address_person1` FOREIGN KEY (`PERSON_ID`) REFERENCES `person` (`PERSON_ID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
